### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by mizerthilez**
Some small fixes!

Best regards!

### CODE REVIEW

**Comment by david04** [comment]
Hey @mizerthilez , I'm going to present the project in a conference in November, and I'd like to give you credit, would you like to send me a very short bio? (maybe a photo also?, so I can add a slide?) please contact me at davidmiguel at antunes [dot] net. Link to conference: https://scala.io/sessions/paris-2024/complex-web-uis-with-fastscala Cheers

**Comment by david04** [comment]
And thanks for the fixes :)

**Comment by mizerthilez** [comment]
Hi David:
Sorry I just saw your message recently. First of all, thanks for your invitation. I am a Scala hobbyist, I am from Shanghai, China, my job is to found and develop a high-performance, high-throughput data extraction and analysis framework for banks to provide support for credit card anti-fraud business. I use Java in work, but I have a very high passion for Scala. I have also developed a prototype of a Web framework using ScalaJs and Binding.scala.

I think FastScala is a very unique project, different from all the ScalaJs-based projects I've seen before, which I think are either too complex and have a high learning curve; or they are difficult to setup and slow to compile; or the functions they provide are too trivial. In web development, it is not easy to combine a fast and easy development process with the abilities to provide rich and powerful features, especially for a language like Scala. And I think FastsScala really does this. So I am very impressed with it and willing to make my own contribution to it. It is my honor to join Fastscala's development, and I hope that through this project, more people will understand and use Scala for web development.

I also particularly like the beautiful and concise syntax of Scala3, and I hope to combine the two. So in my github project, there is a Scala3 branch, which mainly rewrites FastScala using Scala3 syntax similar to Python indentation syntax, and uses ScalaFmt and ScalaFix to automatically adjust the syntax format. In the latest package Form7, I tried to use some new features of Scala3, such as context functions and Scala3 new enum type (I heard that Scala2 Enumeration uses a reflection mechanism, so the performance is not so high.) In the future, I also hope to make some performance improvements to FastScala, such as eliminating the cost of object creation for implicit classes by letting them extending AnyVal.

Finally, I apologize for my poor English writing level :) Hope your conference in November goes smoothly! Cheers!

**Comment by david04** [comment]
Hey @mizerthilez , your english is great :)

Thank you for the kind words :)

If you'd like, please send me a foto of you, your name and email and I'll add a thank you slide!

After the conference I'm planning to take a look at the scala 3 port!

Cheers!

**Pull request merged**
